version: 2

sources:
  - name: motherduck_raw
    database: bank_audit_db
    schema: main
    tables:
      - name: dim_bank_directory

models:
  - name: stg_iban_audit
    columns:
      - name: iban
        tests:
          - not_null
      - name: is_valid
        tests:
          - not_null

  - name: fct_daily_iban_summary
    columns:
      - name: audit_date
        tests:
          - not_null
